spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:tokaido.proxy.rlwy.net}:${DB_PORT:49551}/${DB_NAME:railway}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false

server:
  port: ${PORT:8080}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: PKCS12

logging:
  level:
    root: WARN
    com.villamanager: INFO

