spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/villa_manager_dev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

logging:
  level:
    root: INFO
    com.villamanager: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

