spring:
  application:
    name: villa-manager-backend
  
  datasource:
    url: jdbc:postgresql://hayabusa.proxy.rlwy.net:19979/railway
    username: postgres
    password: YyztViCkWukiwBCYuLtmhjZrEqnzsDCm
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: false
  
  liquibase:
    enabled: false

  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

  sql:
    init:
      mode: never

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: VillaManagerProSecretKeyFor256BitHSAlgorithmMustBeLongEnoughForHS512
    expiration: 86400000

logging:
  level:
    root: INFO
    com.villamanager: DEBUG
    org.springframework.security: DEBUG

